# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_plane.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'control_plane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ontrol_plane.proto\x12\x0f\x63ontrolplane.v1\"v\n\x11\x41gentRegistration\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nagent_type\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x03 \x03(\t\x12\x15\n\rallowed_tools\x18\x04 \x03(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"\x84\x01\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\x12\x14\n\x0cpayload_json\x18\x05 \x01(\t\x12\x1a\n\x12\x64one_criteria_json\x18\x06 \x01(\t\"X\n\tTaskReply\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x19\n\x11\x61ssigned_agent_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"V\n\x0f\x41pprovalRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61pprover\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"*\n\x0bSimpleReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\tTaskQuery\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"a\n\x0fTaskStatusReply\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x19\n\x11\x61ssigned_agent_id\x18\x03 \x01(\t\x12\x12\n\nlast_error\x18\x04 \x01(\t2\xce\x02\n\x13\x43ontrolPlaneService\x12Q\n\rRegisterAgent\x12\".controlplane.v1.AgentRegistration\x1a\x1c.controlplane.v1.SimpleReply\x12\x46\n\nSubmitTask\x12\x1c.controlplane.v1.TaskRequest\x1a\x1a.controlplane.v1.TaskReply\x12M\n\x0b\x41pproveTask\x12 .controlplane.v1.ApprovalRequest\x1a\x1c.controlplane.v1.SimpleReply\x12M\n\rGetTaskStatus\x12\x1a.controlplane.v1.TaskQuery\x1a .controlplane.v1.TaskStatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_plane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTREGISTRATION']._serialized_start=40
  _globals['_AGENTREGISTRATION']._serialized_end=158
  _globals['_TASKREQUEST']._serialized_start=161
  _globals['_TASKREQUEST']._serialized_end=293
  _globals['_TASKREPLY']._serialized_start=295
  _globals['_TASKREPLY']._serialized_end=383
  _globals['_APPROVALREQUEST']._serialized_start=385
  _globals['_APPROVALREQUEST']._serialized_end=471
  _globals['_SIMPLEREPLY']._serialized_start=473
  _globals['_SIMPLEREPLY']._serialized_end=515
  _globals['_TASKQUERY']._serialized_start=517
  _globals['_TASKQUERY']._serialized_end=545
  _globals['_TASKSTATUSREPLY']._serialized_start=547
  _globals['_TASKSTATUSREPLY']._serialized_end=644
  _globals['_CONTROLPLANESERVICE']._serialized_start=647
  _globals['_CONTROLPLANESERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
